
import React from 'react';
import Layout from '@/components/layout/Layout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckIcon } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { PRICE_PER_MILLION_INPUT_TOKENS, PRICE_PER_MILLION_OUTPUT_TOKENS } from '@/contexts/UsageContext';

const Pricing = () => {
  const navigate = useNavigate();
  const { user } = useAuth();

  const features = [
    "AI-powered text classification",
    "Excel file import and export",
    "Custom categories and descriptions",
    "Example-based learning",
    "Detailed usage analytics",
    "User authentication and security",
  ];

  return (
    <Layout>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Simple, Token-Based Pricing</h1>
          <p className="text-xl text-gray-600 mb-16 max-w-2xl mx-auto">
            Our transparent pricing model ensures you only pay for what you use, with no hidden fees or subscriptions.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
            {/* Input Tokens Pricing */}
            <Card className="border-gray-200 text-left shadow-sm hover:shadow-md transition-shadow">
              <CardHeader className="pb-4">
                <CardTitle className="text-2xl">Input Tokens</CardTitle>
                <CardDescription>
                  Tokens used when processing your text, categories, and examples
                </CardDescription>
              </CardHeader>
              <CardContent className="pb-6">
                <div className="mt-2 mb-6">
                  <span className="text-4xl font-bold">€{PRICE_PER_MILLION_INPUT_TOKENS}</span>
                  <span className="text-gray-500 ml-2">per million tokens</span>
                </div>
                <p className="text-sm text-gray-600 mb-4">
                  Input tokens include:
                </p>
                <ul className="space-y-2">
                  <li className="flex">
                    <CheckIcon className="h-5 w-5 text-green-500 mr-2 flex-shrink-0" />
                    <span className="text-gray-600 text-sm">Your uploaded text to be classified</span>
                  </li>
                  <li className="flex">
                    <CheckIcon className="h-5 w-5 text-green-500 mr-2 flex-shrink-0" />
                    <span className="text-gray-600 text-sm">Category names and descriptions</span>
                  </li>
                  <li className="flex">
                    <CheckIcon className="h-5 w-5 text-green-500 mr-2 flex-shrink-0" />
                    <span className="text-gray-600 text-sm">Example text and categories</span>
                  </li>
                  <li className="flex">
                    <CheckIcon className="h-5 w-5 text-green-500 mr-2 flex-shrink-0" />
                    <span className="text-gray-600 text-sm">System instructions for the AI</span>
                  </li>
                </ul>
              </CardContent>
              <CardFooter>
                <Button 
                  className="w-full bg-enlable-500 hover:bg-enlable-600"
                  onClick={() => navigate(user ? '/profile' : '/signup')}
                >
                  {user ? 'Top Up Balance' : 'Get Started'}
                </Button>
              </CardFooter>
            </Card>

            {/* Output Tokens Pricing */}
            <Card className="border-gray-200 text-left shadow-sm hover:shadow-md transition-shadow">
              <CardHeader className="pb-4">
                <CardTitle className="text-2xl">Output Tokens</CardTitle>
                <CardDescription>
                  Tokens generated by our AI when classifying your text
                </CardDescription>
              </CardHeader>
              <CardContent className="pb-6">
                <div className="mt-2 mb-6">
                  <span className="text-4xl font-bold">€{PRICE_PER_MILLION_OUTPUT_TOKENS}</span>
                  <span className="text-gray-500 ml-2">per million tokens</span>
                </div>
                <p className="text-sm text-gray-600 mb-4">
                  Output tokens include:
                </p>
                <ul className="space-y-2">
                  <li className="flex">
                    <CheckIcon className="h-5 w-5 text-green-500 mr-2 flex-shrink-0" />
                    <span className="text-gray-600 text-sm">AI-generated classification results</span>
                  </li>
                  <li className="flex">
                    <CheckIcon className="h-5 w-5 text-green-500 mr-2 flex-shrink-0" />
                    <span className="text-gray-600 text-sm">Response formatting and structure</span>
                  </li>
                  <li className="flex">
                    <CheckIcon className="h-5 w-5 text-green-500 mr-2 flex-shrink-0" />
                    <span className="text-gray-600 text-sm">Any additional explanations from the AI</span>
                  </li>
                </ul>
              </CardContent>
              <CardFooter>
                <Button 
                  className="w-full bg-enlable-500 hover:bg-enlable-600"
                  onClick={() => navigate(user ? '/profile' : '/signup')}
                >
                  {user ? 'Top Up Balance' : 'Get Started'}
                </Button>
              </CardFooter>
            </Card>
          </div>

          {/* Features Section */}
          <div className="bg-gray-50 rounded-xl p-8 border border-gray-100">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">All Features Included</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-2xl mx-auto">
              {features.map((feature, index) => (
                <div key={index} className="flex items-start">
                  <div className="flex-shrink-0 mt-1">
                    <CheckIcon className="h-5 w-5 text-enlable-500" />
                  </div>
                  <p className="ml-3 text-base text-gray-600">{feature}</p>
                </div>
              ))}
            </div>
          </div>

          {/* FAQ Section */}
          <div className="mt-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-8">Frequently Asked Questions</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left">
              <div className="bg-white p-6 rounded-xl border border-gray-200">
                <h3 className="text-lg font-medium text-gray-900 mb-2">How do I pay for the service?</h3>
                <p className="text-gray-600">
                  You can top up your account balance in your profile. Your usage costs will be deducted from your balance as you use the service.
                </p>
              </div>
              
              <div className="bg-white p-6 rounded-xl border border-gray-200">
                <h3 className="text-lg font-medium text-gray-900 mb-2">What happens if I run out of balance?</h3>
                <p className="text-gray-600">
                  You'll need to top up your balance before you can continue using the service. We'll warn you when your balance is running low.
                </p>
              </div>
              
              <div className="bg-white p-6 rounded-xl border border-gray-200">
                <h3 className="text-lg font-medium text-gray-900 mb-2">Is there a minimum payment amount?</h3>
                <p className="text-gray-600">
                  The minimum amount you can add to your balance is €10. This ensures you have enough to process a reasonable amount of text.
                </p>
              </div>
              
              <div className="bg-white p-6 rounded-xl border border-gray-200">
                <h3 className="text-lg font-medium text-gray-900 mb-2">How accurate is the token count estimate?</h3>
                <p className="text-gray-600">
                  Our token estimates are approximations based on character count. The actual token count may vary slightly. You'll only be charged for actual tokens used.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Pricing;
