// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxugfaprgrjerilzulxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4dWdmYXByZ3JqZXJpbHp1bHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTkwNjUsImV4cCI6MjA1ODM5NTA2NX0.Gwj_LUlnCS0HAWJsCuqco4CZihpULV41StoWslR_8gE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);